language: python
python:
    - "2.7"

services:
    - mysql

install: "pip install -r support/requirements.txt"

before_install:
    - export DJANGO_SETTINGS_MODULE=trackersite.travis_settings
    - export PYTHONPATH=$(pwd)
    - export DEPLOY_DIR=$(pwd)/deploy
    - mkdir -p ${DEPLOY_DIR}/{,docs}

script: "python trackersite/manage.py test --verbosity 2"
